// This file was auto-generated by SceneListCheck!

public enum Scenes 
{
	Menu = 0,
	Level_1 = 1,
	Level_2 = 2,
	Level_3 = 3,
	Level_4 = 4,
	Level_5 = 5,
	Level_6 = 6,
	Level_7 = 7,
	Level_8 = 8,
	Level_9 = 9,
	Level_10 = 10,
	Level_11 = 11,
	Credits = 12,
	UIScene = 13
}

